### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mpowelson** [denabazazian/Edge_Extraction#1]
What license is this released under? We are interested in using an algorithm such as this in an industrial robotics application. For our use case we require any software we use be released under a permissive license such as Apache 2.0.

**Comment by denabazazian** [comment]
Thanks @mpowelson for your interest in our algorithm. We have released this repository under the [MIT license](https://github.com/denabazazian/Edge_Extraction/blob/master/LICENSE). Hope this clarifies your query.

**Comment by mpowelson** [comment]
That's great. Thanks
