### ISSUE TITLE
Saving the output

### ISSUE THREAD

**Issue by iKessho** [denabazazian/Edge_Extraction#2]
Hi,

Am using the python version of your code.
Am wondering how do you save the generated edges into a obj/ply file?
I see the output in a graph but i want to use the actual points in the edges for further processing

Many Thanks.

**Comment by denabazazian** [comment]
Hi @iKessho, 
Thanks for your interest in this repository, I have updated the code code to save the edges as a ply file. You can check the lines 87 and 88. 
'pointcloud_edges.ply' is for saving the whole point cloud by painting the edge points and 'edges.ply' is for saving just the edge points that extracted through this algorithm. 

If you still have any problem with it feel free to open the issue again.
