### ISSUE TITLE
Error when running python file

### ISSUE THREAD

**Issue by trinhnhut-gif** [denabazazian/Edge_Extraction#6]
Hello,
When I run your python file, I have some problems below.  And I also tried to fix that. Do you have any suggestions for me? Thank you
![image](https://user-images.githubusercontent.com/85855232/194204537-f562b231-8da0-4fb0-b70e-b6f1d2374bb6.png)

**Comment by denabazazian** [comment]
Thanks for using this code. 
This error comes from a conflict in the version of either Scipy or Pyntcloud. 
` TypeError: Unexpected keyword argument {'n_jobs': -1}` is an error regarding the version of the `scipy` that you installed. 
According to `scipy.spatial.cKDTree.query` [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query.html#scipy.spatial.cKDTree.query), n_jobs is deprecated starting from scipy>=1.9.0. 
Therefore, with `scipy >= 1.9.0`, this leads to an error in `Difference_Eigenvalues.py`.
